// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
		"/mongo/insert-one": {
            "post": {
                "description": "create project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "RequestOne of creating project",
                        "name": "RequestOne",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mongoRequest.RequestOne"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mongo.insertId"
                        }
                    }
                }
            }
        }
	},
    "definitions": {
        "mongoRequest.RequestOne": {
            "type": "object",
            "properties": {
                "name": {
                    "type":"string"
                },
                "age": {
                    "type":"string"
                },
                "cve": {
                    "type":"string"
                },
                "dep": {
                    "type":"string"
                },
                "repo": {
                    "type":"string"
                }
            }
        },
        "mongo.insertId": {
            "type": "string"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
